### PR TITLE
RNUrlPreview into functional component

### PR DESCRIPTION
**Pull request by ZenVega**
I didn't manage to get it running yet since i never used react-native before. Nevertheless, I tried to restructure it already.

### CODE REVIEW

**Comment by maherzaidoune** [comment]
> I didn't manage to get it running yet since i never used react-native before. Nevertheless, I tried to restructure it already.

I'll check that this week

**Comment by Hosam-hsm** [comment]
Working fine. A slight change required is to change useEffect to :
 
 useEffect(() => {
        if (props.text) {
            getPreview(props.text);
        } else if (props.text == null) {
            setIsUri(false);
        }
    }, [props.text]);

**Comment by ZenVega** [comment]
Alrighty

**Comment by mir1198yusuf** [comment]
is this PR merged ?
master branch still uses class component..

**Pull request closed without merging**
